"""create esi_band table

Revision ID: 03ba37a42a4d
Revises: 3580546ec0b8
Create Date: 2026-07-08 09:53:53.230021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ba37a42a4d'
down_revision: Union[str, Sequence[str], None] = '3580546ec0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esi_band',
    sa.Column('band_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=False),
    sa.Column('esi_level', sa.String(length=8), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('meaning', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('band_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esi_band')
    # ### end Alembic commands ###
