"""create feedback_response table

Revision ID: 0838346c6143
Revises: 4c0692ca4084
Create Date: 2026-07-08 10:11:12.542912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0838346c6143'
down_revision: Union[str, Sequence[str], None] = '4c0692ca4084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ai_priority', sa.String(length=12), nullable=True),
    sa.Column('final_priority', sa.String(length=12), nullable=True),
    sa.Column('changed_decision', sa.Boolean(), nullable=True),
    sa.Column('feedback_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['feedback_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_feedback_response_session_id'), 'feedback_response', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_response_session_id'), table_name='feedback_response')
    op.drop_table('feedback_response')
    # ### end Alembic commands ###
