"""patient.date_of_birth to Date; intake_record jsonb rows default to []

Revision ID: 1bcfe72fee6e
Revises: 84d4ee147692
Create Date: 2026-07-12 16:50:35.656943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bcfe72fee6e'
down_revision: Union[str, Sequence[str], None] = '84d4ee147692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using="date_of_birth::date")
    
    op.alter_column('intake_record', 'symptoms',
                server_default='[]',
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                existing_nullable=True)
    op.alter_column('intake_record', 'missing_fields',
                server_default='[]',
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                existing_nullable=True)
    op.alter_column('intake_record', 'pre_existing_conditions',
                server_default='[]',
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'date_of_birth',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               postgresql_using="date_of_birth::timestamp with time zone")
    
    op.alter_column('intake_record', 'symptoms',
                server_default='{}',
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                existing_nullable=True)
    op.alter_column('intake_record', 'missing_fields',
                server_default='{}',
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                existing_nullable=True)
    op.alter_column('intake_record', 'pre_existing_conditions',
                server_default='{}',
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                existing_nullable=True)
    # ### end Alembic commands ###
