"""Seed esi_band table

Revision ID: 2d40157e2db3
Revises: 0838346c6143
Create Date: 2026-07-08 10:36:54.591835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = '2d40157e2db3'
down_revision: Union[str, Sequence[str], None] = '0838346c6143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    esi_band_helper = table('esi_band',
        column('band_id', sa.Integer),
        column('min_points', sa.Integer),
        column('max_points', sa.Integer),
        column('esi_level', sa.String),
        column('priority', sa.String),
        column('meaning', sa.String)
    )

    op.bulk_insert(esi_band_helper, [
        {"band_id": 1, "min_points": 8, "max_points": 99, "esi_level": "ESI-1", "priority": "Highest", "meaning": "Immediate — resuscitation"},
        {"band_id": 2, "min_points": 6, "max_points": 7, "esi_level": "ESI-2", "priority": "High", "meaning": "Emergent — rapid placement"},
        {"band_id": 3, "min_points": 3, "max_points": 5, "esi_level": "ESI-3", "priority": "Medium", "meaning": "Urgent — needs resources"},
        {"band_id": 4, "min_points": 1, "max_points": 2, "esi_level": "ESI-4", "priority": "Low", "meaning": "Less urgent — one resource"},
        {"band_id": 5, "min_points": 0, "max_points": 0, "esi_level": "ESI-5", "priority": "Lowest", "meaning": "Non-urgent — fast-track"}
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    esi_band_helper = table('esi_band', column('band_id', sa.Integer))
    op.execute(esi_band_helper.delete().where(esi_band_helper.c.band_id.in_([1, 2, 3, 4, 5])))
