"""create vital_range table

Revision ID: 3580546ec0b8
Revises: 8cd31a0b9895
Create Date: 2026-07-08 09:47:56.417079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3580546ec0b8'
down_revision: Union[str, Sequence[str], None] = '8cd31a0b9895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vital_range',
    sa.Column('vital_range_id', sa.Integer(), nullable=False),
    sa.Column('vital_name', sa.String(length=30), nullable=False),
    sa.Column('age_group', sa.String(length=20), server_default='adult', nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('vital_range_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vital_range')
    # ### end Alembic commands ###
