"""Added intake_record.notes

Revision ID: 36b375efcced
Revises: f8ad900ea6e8
Create Date: 2026-08-03 22:24:53.448125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b375efcced'
down_revision: Union[str, Sequence[str], None] = 'f8ad900ea6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake_record', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake_record', 'notes')
    # ### end Alembic commands ###
