"""Added triage_queue sort key fields

Revision ID: 3f8f58889e3a
Revises: 57cd4ed9dfd3
Create Date: 2026-08-22 23:30:18.026507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8f58889e3a'
down_revision: Union[str, Sequence[str], None] = '57cd4ed9dfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_queue', sa.Column('esi_band', sa.Integer(), nullable=False))
    op.add_column('triage_queue', sa.Column('flag_tier', sa.Integer(), nullable=False))
    op.add_column('triage_queue', sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False))
    op.create_check_constraint('check_esi_band', 'triage_queue', 'esi_band >= 1 AND esi_band <= 5')
    op.create_check_constraint('check_flag_tier', 'triage_queue', 'flag_tier >= 1 AND flag_tier <= 3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_esi_band', 'triage_queue', type_='check')
    op.drop_constraint('check_flag_tier', 'triage_queue', type_='check')
    op.drop_column('triage_queue', 'arrival_time')
    op.drop_column('triage_queue', 'flag_tier')
    op.drop_column('triage_queue', 'esi_band')
    # ### end Alembic commands ###
