"""create ai_explanation table

Revision ID: 43692cc7c97c
Revises: b5cf52b64fda
Create Date: 2026-07-07 12:35:18.186450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43692cc7c97c'
down_revision: Union[str, Sequence[str], None] = 'b5cf52b64fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_explanation',
    sa.Column('explanation_id', sa.Integer(), nullable=False),
    sa.Column('severity_id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('explanation_text', sa.String(), nullable=False),
    sa.Column('factor_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('step', sa.String(length=8), nullable=True),
    sa.Column('lead_element', sa.String(length=24), nullable=True),
    sa.Column('model_used', sa.String(length=40), server_default='rule-based template', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intake_record.intake_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['severity_id'], ['patient_severity.severity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('explanation_id')
    )
    op.create_index(op.f('ix_ai_explanation_intake_id'), 'ai_explanation', ['intake_id'], unique=False)
    op.create_index(op.f('ix_ai_explanation_severity_id'), 'ai_explanation', ['severity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_explanation_severity_id'), table_name='ai_explanation')
    op.drop_index(op.f('ix_ai_explanation_intake_id'), table_name='ai_explanation')
    op.drop_table('ai_explanation')
    # ### end Alembic commands ###
