"""create feedback_session table

Revision ID: 4c0692ca4084
Revises: d858061ca815
Create Date: 2026-07-08 10:07:19.160047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0692ca4084'
down_revision: Union[str, Sequence[str], None] = 'd858061ca815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tester_type', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_session')
    # ### end Alembic commands ###
