"""add JSON tree for red_flag_rule

Revision ID: 53cecf75710b
Revises: 93b6d72bdb62
Create Date: 2026-07-26 13:30:56.964906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53cecf75710b'
down_revision: Union[str, Sequence[str], None] = '93b6d72bdb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM red_flag_rule")
    op.add_column('red_flag_rule', sa.Column('trigger_pattern_tree', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('red_flag_rule', 'trigger_pattern_tree')
    # ### end Alembic commands ###
