"""scoring_rule.esi_anchor non-null

Revision ID: 57cd4ed9dfd3
Revises: 36b375efcced
Create Date: 2026-08-13 10:35:41.521293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cd4ed9dfd3'
down_revision: Union[str, Sequence[str], None] = '36b375efcced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scoring_rule', 'esi_anchor',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scoring_rule', 'esi_anchor',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
