"""Fixed accidental change to temperature vs blood_sugar

Revision ID: 58234caa72cd
Revises: cf8fc2ac65dc
Create Date: 2026-07-21 12:43:28.546673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58234caa72cd'
down_revision: Union[str, Sequence[str], None] = 'cf8fc2ac65dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intake_record', 'temperature',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=True)
    op.alter_column('intake_record', 'blood_sugar',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intake_record', 'blood_sugar',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.NUMERIC(precision=4, scale=1),
               existing_nullable=True)
    op.alter_column('intake_record', 'temperature',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.NUMERIC(precision=5, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
