"""added unique constraint to triage_queue.intake_id

Revision ID: 5b2db13689cc
Revises: c0f7625fd548
Create Date: 2026-08-24 11:53:16.493375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2db13689cc'
down_revision: Union[str, Sequence[str], None] = 'c0f7625fd548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_queue_intake_id'), table_name='triage_queue')
    op.create_index(op.f('ix_triage_queue_intake_id'), 'triage_queue', ['intake_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_queue_intake_id'), table_name='triage_queue')
    op.create_index(op.f('ix_triage_queue_intake_id'), 'triage_queue', ['intake_id'], unique=False)
    # ### end Alembic commands ###
