"""added indexing to triage_queue

Revision ID: 5fbb7f37f8b7
Revises: 3f8f58889e3a
Create Date: 2026-08-23 21:01:27.625077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbb7f37f8b7'
down_revision: Union[str, Sequence[str], None] = '3f8f58889e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_triage_queue_sort_key', 'triage_queue', ['esi_band', 'flag_tier', 'arrival_time', 'intake_id'], unique=False)
    op.create_index(op.f('ix_triage_queue_status'), 'triage_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_queue_status'), table_name='triage_queue')
    op.drop_index('ix_triage_queue_sort_key', table_name='triage_queue')
    # ### end Alembic commands ###
