"""Add scoring_rule columns

Revision ID: 683e3ac598e4
Revises: 58234caa72cd
Create Date: 2026-07-21 17:27:02.462469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683e3ac598e4'
down_revision: Union[str, Sequence[str], None] = '58234caa72cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM scoring_rule")
    op.add_column('scoring_rule', sa.Column('rule_type', sa.String(length=10), nullable=False))
    op.add_column('scoring_rule', sa.Column('min_bound', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('scoring_rule', sa.Column('max_bound', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('scoring_rule', sa.Column('units', sa.String(length=10), nullable=True))
    op.add_column('scoring_rule', sa.Column('threshold_display', sa.String(length=60), nullable=False))
    op.alter_column('scoring_rule', 'esi_anchor',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.drop_column('scoring_rule', 'threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoring_rule', sa.Column('threshold', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.alter_column('scoring_rule', 'esi_anchor',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    op.drop_column('scoring_rule', 'threshold_display')
    op.drop_column('scoring_rule', 'units')
    op.drop_column('scoring_rule', 'max_bound')
    op.drop_column('scoring_rule', 'min_bound')
    op.drop_column('scoring_rule', 'rule_type')
    # ### end Alembic commands ###
