"""create system_metric table

Revision ID: 6c3879140011
Revises: b517e1873b69
Create Date: 2026-07-07 12:44:34.807446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3879140011'
down_revision: Union[str, Sequence[str], None] = 'b517e1873b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metric',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=60), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('metric_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_metric')
    # ### end Alembic commands ###
