"""create patient_severity table, update patient and intake_record tables

Revision ID: 816e0598eeba
Revises: 8c23f5e2c66d
Create Date: 2026-07-07 11:51:35.414373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '816e0598eeba'
down_revision: Union[str, Sequence[str], None] = '8c23f5e2c66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_severity',
    sa.Column('severity_id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('severity_score', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('system_ESI', sa.String(length=8), nullable=True),
    sa.Column('clinician_ESI', sa.String(length=8), nullable=True),
    sa.Column('score_reason', sa.String(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('red_flag_fired', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('severity_score >= 0 and severity_score <= 100', name='check_severity_score'),
    sa.ForeignKeyConstraint(['intake_id'], ['intake_record.intake_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('severity_id')
    )
    op.create_index(op.f('ix_patient_severity_intake_id'), 'patient_severity', ['intake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_severity_intake_id'), table_name='patient_severity')
    op.drop_table('patient_severity')
    # ### end Alembic commands ###
