"""Lengthened column evidence_source in red_flag_rule

Revision ID: 84d4ee147692
Revises: a5158cbb3a57
Create Date: 2026-07-12 15:58:25.916831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d4ee147692'
down_revision: Union[str, Sequence[str], None] = 'a5158cbb3a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('red_flag_rule', 'evidence_source',
               existing_type=sa.String(length=60),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('red_flag_rule', 'evidence_source',
               existing_type=sa.String(length=120),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###
