"""create event_log table

Revision ID: 8b56261b3cd8
Revises: 6c3879140011
Create Date: 2026-07-07 12:49:53.407945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b56261b3cd8'
down_revision: Union[str, Sequence[str], None] = '6c3879140011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('intake_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intake_record.intake_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_event_log_intake_id'), 'event_log', ['intake_id'], unique=False)
    op.create_index(op.f('ix_event_log_patient_id'), 'event_log', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_log_patient_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_intake_id'), table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###
