"""create intake_record table

Revision ID: 8c23f5e2c66d
Revises: 905a26f17a74
Create Date: 2026-07-07 11:38:32.869152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c23f5e2c66d'
down_revision: Union[str, Sequence[str], None] = '905a26f17a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_record',
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('chief_complaint', sa.String(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('oxygen_saturation', sa.Integer(), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('blood_sugar', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('source', sa.String(), server_default='form', nullable=False),
    sa.Column('external_patient_id', sa.String(), nullable=True),
    sa.Column('actual_outcome', sa.String(), nullable=True),
    sa.Column('outcome_source', sa.String(), nullable=True),
    sa.Column('pregnancy_status', sa.String(), nullable=True),
    sa.Column('pre_existing_conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('arrival_by_ambulance', sa.Boolean(), nullable=True),
    sa.Column('recent_ed_visit_72h', sa.Boolean(), nullable=True),
    sa.Column('injury_related', sa.Boolean(), nullable=True),
    sa.Column('respiration_rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pain_level >= 0 and pain_level <= 10', name='check_pain_level'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intake_id')
    )
    op.create_index(op.f('ix_intake_record_patient_id'), 'intake_record', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intake_record_patient_id'), table_name='intake_record')
    op.drop_table('intake_record')
    # ### end Alembic commands ###
