"""create red_flag_rule table

Revision ID: 8cd31a0b9895
Revises: 94c97394f5a7
Create Date: 2026-07-08 09:42:28.823371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd31a0b9895'
down_revision: Union[str, Sequence[str], None] = '94c97394f5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('red_flag_rule',
    sa.Column('vital_range_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('trigger_pattern', sa.String(length=200), nullable=False),
    sa.Column('flag_type', sa.String(length=20), nullable=False),
    sa.Column('flag_tier', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=160), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('evidence_source', sa.String(length=60), nullable=False),
    sa.Column('outcome_validated', sa.String(length=20), nullable=False),
    sa.Column('requires_field', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('vital_range_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('red_flag_rule')
    # ### end Alembic commands ###
