"""scoring_rule.fallback_is_missing cannot be null

Revision ID: 93b6d72bdb62
Revises: cbe41910c926
Create Date: 2026-07-22 16:29:36.131417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b6d72bdb62'
down_revision: Union[str, Sequence[str], None] = 'cbe41910c926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scoring_rule', 'fallback_if_missing',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scoring_rule', 'fallback_if_missing',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
