"""create scoring_rule table

Revision ID: 94c97394f5a7
Revises: f5c670630d96
Create Date: 2026-07-08 09:37:15.464302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c97394f5a7'
down_revision: Union[str, Sequence[str], None] = 'f5c670630d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_rule',
    sa.Column('rule_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('factor', sa.String(length=40), nullable=False),
    sa.Column('threshold', sa.String(length=60), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('complaint_group', sa.String(length=40), nullable=True),
    sa.Column('resource_level', sa.String(length=8), nullable=True),
    sa.Column('esi_anchor', sa.String(length=60), nullable=True),
    sa.Column('fallback_if_missing', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoring_rule')
    # ### end Alembic commands ###
