"""Corrected red_flag_rule column name

Revision ID: a5158cbb3a57
Revises: 0838346c6143
Create Date: 2026-07-12 15:36:44.201155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5158cbb3a57'
down_revision: Union[str, Sequence[str], None] = '0838346c6143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('red_flag_rule', 'vital_range_id', new_column_name='flag_id', existing_type=sa.Integer(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('red_flag_rule', 'flag_id', new_column_name='vital_range_id', existing_type=sa.Integer(), existing_nullable=False)
    # ### end Alembic commands ###
