"""create override table

Revision ID: b517e1873b69
Revises: 43692cc7c97c
Create Date: 2026-07-07 12:40:47.576714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b517e1873b69'
down_revision: Union[str, Sequence[str], None] = '43692cc7c97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('override',
    sa.Column('override_id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('severity_id', sa.Integer(), nullable=False),
    sa.Column('system_ESI', sa.String(length=8), nullable=False),
    sa.Column('clinician_ESI', sa.String(length=8), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intake_record.intake_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['severity_id'], ['patient_severity.severity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('override_id')
    )
    op.create_index(op.f('ix_override_intake_id'), 'override', ['intake_id'], unique=False)
    op.create_index(op.f('ix_override_severity_id'), 'override', ['severity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_override_severity_id'), table_name='override')
    op.drop_index(op.f('ix_override_intake_id'), table_name='override')
    op.drop_table('override')
    # ### end Alembic commands ###
