"""create case_update table

Revision ID: b5cf52b64fda
Revises: d07ff5415625
Create Date: 2026-07-07 12:28:58.416990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5cf52b64fda'
down_revision: Union[str, Sequence[str], None] = 'd07ff5415625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_update',
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('updated_symptoms', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('updated_vitals', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('reason_for_update', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intake_record.intake_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_index(op.f('ix_case_update_intake_id'), 'case_update', ['intake_id'], unique=False)
    op.create_index(op.f('ix_case_update_patient_id'), 'case_update', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_update_patient_id'), table_name='case_update')
    op.drop_index(op.f('ix_case_update_intake_id'), table_name='case_update')
    op.drop_table('case_update')
    # ### end Alembic commands ###
