"""added scoring_status column to intake_record

Revision ID: c0f7625fd548
Revises: 5fbb7f37f8b7
Create Date: 2026-08-23 22:29:09.666915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f7625fd548'
down_revision: Union[str, Sequence[str], None] = '5fbb7f37f8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake_record', sa.Column('scoring_status', sa.String(length=20), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake_record', 'scoring_status')
    # ### end Alembic commands ###
