"""Added columns to scoring_rule

Revision ID: c124ff21fbb4
Revises: 53cecf75710b
Create Date: 2026-07-27 21:39:27.415854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c124ff21fbb4'
down_revision: Union[str, Sequence[str], None] = '53cecf75710b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM scoring_rule")
    op.add_column('scoring_rule', sa.Column('scoring_action', sa.String(length=16), nullable=True))
    op.add_column('scoring_rule', sa.Column('confidence_effect', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scoring_rule', 'confidence_effect')
    op.drop_column('scoring_rule', 'scoring_action')
    # ### end Alembic commands ###
