"""Edited patient_severity columns

Revision ID: cbe41910c926
Revises: 683e3ac598e4
Create Date: 2026-07-22 11:48:35.828436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbe41910c926'
down_revision: Union[str, Sequence[str], None] = '683e3ac598e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_severity', sa.Column('fallbacks_applied', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.add_column('patient_severity', sa.Column('confidence', sa.String(length=8), nullable=True))
    op.drop_column('patient_severity', 'fallback_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_severity', sa.Column('fallback_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('patient_severity', 'confidence')
    op.drop_column('patient_severity', 'fallbacks_applied')
    # ### end Alembic commands ###
