"""create guideline_snippet table

Revision ID: cc3ada8e3e87
Revises: 03ba37a42a4d
Create Date: 2026-07-08 09:58:21.204364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc3ada8e3e87'
down_revision: Union[str, Sequence[str], None] = '03ba37a42a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guideline_snippet',
    sa.Column('guideline_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=True),
    sa.Column('snippet_text', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(length=120), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guideline_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guideline_snippet')
    # ### end Alembic commands ###
