"""Add patent_severity.flag_tier; remove triage_queue columns

Revision ID: cf8fc2ac65dc
Revises: e5858483ae35
Create Date: 2026-07-20 21:26:34.123557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8fc2ac65dc'
down_revision: Union[str, Sequence[str], None] = 'e5858483ae35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_severity', sa.Column('flag_tier', sa.Integer(), server_default='3', nullable=False))
    op.drop_column('triage_queue', 'severity_score')
    op.drop_column('triage_queue', 'queue_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_queue', sa.Column('queue_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('triage_queue', sa.Column('severity_score', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False))
    op.drop_column('patient_severity', 'flag_tier')
    # ### end Alembic commands ###
