"""create triage_queue table

Revision ID: d07ff5415625
Revises: 303ba0c3123b
Create Date: 2026-07-07 12:21:33.009699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07ff5415625'
down_revision: Union[str, Sequence[str], None] = '303ba0c3123b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_queue',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('severity_id', sa.Integer(), nullable=False),
    sa.Column('severity_score', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='WAITING', nullable=False),
    sa.Column('entered_queue_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intake_record.intake_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['severity_id'], ['patient_severity.severity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_index(op.f('ix_triage_queue_intake_id'), 'triage_queue', ['intake_id'], unique=False)
    op.create_index(op.f('ix_triage_queue_patient_id'), 'triage_queue', ['patient_id'], unique=False)
    op.create_index(op.f('ix_triage_queue_severity_id'), 'triage_queue', ['severity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_queue_severity_id'), table_name='triage_queue')
    op.drop_index(op.f('ix_triage_queue_patient_id'), table_name='triage_queue')
    op.drop_index(op.f('ix_triage_queue_intake_id'), table_name='triage_queue')
    op.drop_table('triage_queue')
    # ### end Alembic commands ###
