"""create retrieval_log table

Revision ID: d858061ca815
Revises: cc3ada8e3e87
Create Date: 2026-07-08 10:03:32.284567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd858061ca815'
down_revision: Union[str, Sequence[str], None] = 'cc3ada8e3e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_log',
    sa.Column('retrieval_id', sa.Integer(), nullable=False),
    sa.Column('explanation_id', sa.Integer(), nullable=False),
    sa.Column('guideline_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['explanation_id'], ['ai_explanation.explanation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guideline_id'], ['guideline_snippet.guideline_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('retrieval_id')
    )
    op.create_index(op.f('ix_retrieval_log_explanation_id'), 'retrieval_log', ['explanation_id'], unique=False)
    op.create_index(op.f('ix_retrieval_log_guideline_id'), 'retrieval_log', ['guideline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_log_guideline_id'), table_name='retrieval_log')
    op.drop_index(op.f('ix_retrieval_log_explanation_id'), table_name='retrieval_log')
    op.drop_table('retrieval_log')
    # ### end Alembic commands ###
