"""Updated blood_sugar precision

Revision ID: e5858483ae35
Revises: f8d2d0882c74
Create Date: 2026-07-15 19:46:19.721827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5858483ae35'
down_revision: Union[str, Sequence[str], None] = 'f8d2d0882c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intake_record', 'temperature',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intake_record', 'temperature',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.NUMERIC(precision=4, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
