"""Added details to event_log

Revision ID: f4bb6320f341
Revises: c124ff21fbb4
Create Date: 2026-07-28 15:46:33.678880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4bb6320f341'
down_revision: Union[str, Sequence[str], None] = 'c124ff21fbb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_log', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_log', 'details')
    # ### end Alembic commands ###
