"""create condition_reference table

Revision ID: f5c670630d96
Revises: 83972187ccc4
Create Date: 2026-07-08 09:14:32.309448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c670630d96'
down_revision: Union[str, Sequence[str], None] = '83972187ccc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_reference',
    sa.Column('condition_reference_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.String(length=80), nullable=False),
    sa.Column('match_type', sa.String(length=12), nullable=False),
    sa.Column('complaint_key', sa.String(length=40), nullable=True),
    sa.Column('context_condition', sa.String(length=80), nullable=True),
    sa.Column('icd10_prefixes', sa.String(length=80), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=False),
    sa.Column('admitted', sa.Integer(), nullable=False),
    sa.Column('admit_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reliable', sa.String(length=12), nullable=False),
    sa.Column('triage_note', sa.String(length=120), nullable=True),
    sa.Column('source_label', sa.String(length=120), server_default='NHAMCS 2022', nullable=False),
    sa.PrimaryKeyConstraint('condition_reference_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition_reference')
    # ### end Alembic commands ###
