"""Add columns to ai_explanation

Revision ID: f8ad900ea6e8
Revises: f4bb6320f341
Create Date: 2026-07-29 16:11:49.240008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8ad900ea6e8'
down_revision: Union[str, Sequence[str], None] = 'f4bb6320f341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_explanation', sa.Column('data_completeness', sa.String(length=20), nullable=False))
    op.add_column('ai_explanation', sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_explanation', 'gaps')
    op.drop_column('ai_explanation', 'data_completeness')
    # ### end Alembic commands ###
